/*Exercício 3 a*/
ALTER TABLE DEP_DEPENDENTE DROP COLUMN PARENTESCO;
CREATE TABLE PAR_PARENTESCO (
    CODIGO NUMBER(4) PRIMARY KEY,
    DESCRICAO VARCHAR2(100) NOT NULL
);
ALTER TABLE DEP_DEPENDENTE ADD (
    COD_PARENTESCO NUMBER(4) NOT NULL,
    CONSTRAINT FK_PARENTESCO_DEPENDENTE FOREIGN KEY(COD_PARENTESCO) REFERENCES PAR_PARENTESCO(CODIGO)
);
/*Exercício 3 b*/
ALTER TABLE DEP_DEPENDENTE ADD (
    CPF_DEPENDENTE VARCHAR2(11),
    CONSTRAINT UK_CPF_DEPENDENTE UNIQUE (CPF_DEPENDENTE)
);

/*Exercicio 3 c*/
ALTER TABLE DEP_DEPENDENTE DROP CONSTRAINT FK_COD_FUNC;
ALTER TABLE DEP_DEPENDENTE ADD CONSTRAINT FK_COD_FUNC FOREIGN KEY(COD_FUNC) REFERENCES FUN_FUNCIONARIO(COD_FUNC) ON DELETE CASCADE;

/*Exercício 4 a*/
ALTER TABLE PAR_PARTICIPA RENAME TO FUNC_PROJETO;