cod1, n1, val1 = input().split()
cod2, n2, val2 = input().split()
cod1 = int(cod1)
n1 = int(n1)
val1 = float(val1)
cod2 = int(cod2)
n2 = int(n2)
val2 = float(val2)
total = (n1 * val1) + (n2 * val2)
print("VALOR A PAGAR: R$ %.2f" %total)